# Generated by Django 3.1.2 on 2020-10-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationschedule',
            old_name='medication_schedule',
            new_name='schedule',
        ),
    ]
